"""initial schema

Revision ID: bf156097dca2
Revises: 
Create Date: 2026-06-25 18:30:13.164429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf156097dca2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('responsible_org', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_key')
    )
    op.create_table('raw_dataset_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('dataset_role', sa.String(length=50), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_table('readiness_assessments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('percentage_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readiness_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_key')
    )
    op.create_table('sensor_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('variable_group', sa.String(length=100), nullable=True),
    sa.Column('component_key', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variable_name')
    )
    op.create_table('bcm_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('maximum_tolerable_downtime_min', sa.Integer(), nullable=False),
    sa.Column('recovery_time_objective_min', sa.Integer(), nullable=False),
    sa.Column('backup_available', sa.Boolean(), nullable=True),
    sa.Column('backup_duration_min', sa.Integer(), nullable=True),
    sa.Column('recovery_action', sa.Text(), nullable=True),
    sa.Column('emergency_contact_role', sa.String(length=150), nullable=True),
    sa.Column('last_exercise_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['infrastructure_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id')
    )
    op.create_table('infrastructure_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_component_id', sa.Integer(), nullable=False),
    sa.Column('target_component_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=100), nullable=True),
    sa.Column('criticality', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_component_id'], ['infrastructure_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_component_id'], ['infrastructure_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_component_id', 'target_component_id', name='uq_component_dependency')
    )
    op.create_table('readiness_answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('assessment_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_value', sa.String(length=30), nullable=False),
    sa.Column('numeric_score', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['readiness_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['readiness_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tep_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_file_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('dataset_role', sa.String(length=50), nullable=False),
    sa.Column('fault_id', sa.Integer(), nullable=True),
    sa.Column('fault_label', sa.String(length=150), nullable=True),
    sa.Column('is_faulty', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('variable_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_file_id'], ['raw_dataset_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('baseline_mean', sa.Float(), nullable=True),
    sa.Column('baseline_std', sa.Float(), nullable=True),
    sa.Column('q001', sa.Float(), nullable=True),
    sa.Column('q005', sa.Float(), nullable=True),
    sa.Column('q025', sa.Float(), nullable=True),
    sa.Column('q500', sa.Float(), nullable=True),
    sa.Column('q975', sa.Float(), nullable=True),
    sa.Column('q995', sa.Float(), nullable=True),
    sa.Column('q999', sa.Float(), nullable=True),
    sa.Column('warning_low', sa.Float(), nullable=True),
    sa.Column('warning_high', sa.Float(), nullable=True),
    sa.Column('critical_low', sa.Float(), nullable=True),
    sa.Column('critical_high', sa.Float(), nullable=True),
    sa.Column('derived_from_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variable_id'], ['sensor_variables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variable_id', 'derived_from_role', name='uq_variable_role')
    )
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('root_cause_candidate', sa.String(length=150), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('first_time_step', sa.Integer(), nullable=True),
    sa.Column('last_time_step', sa.Integer(), nullable=True),
    sa.Column('raw_alarm_count', sa.Integer(), nullable=True),
    sa.Column('unique_alarm_count', sa.Integer(), nullable=True),
    sa.Column('affected_component_count', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['tep_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('time_step', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('variable_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['tep_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variable_id'], ['sensor_variables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarm_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=True),
    sa.Column('time_step', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=True),
    sa.Column('component_key', sa.String(length=100), nullable=True),
    sa.Column('alarm_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('deviation_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('duplicate_group_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['sensor_observations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['tep_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variable_id'], ['sensor_variables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('incident_id', sa.BigInteger(), nullable=False),
    sa.Column('scenario_name', sa.String(length=150), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_interruption_min', sa.Integer(), nullable=True),
    sa.Column('continuity_risk', sa.String(length=30), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_alarm_events',
    sa.Column('incident_id', sa.BigInteger(), nullable=False),
    sa.Column('alarm_event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['alarm_event_id'], ['alarm_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'alarm_event_id')
    )
    op.create_table('simulation_impact_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('simulation_run_id', sa.BigInteger(), nullable=False),
    sa.Column('minute_offset', sa.Integer(), nullable=False),
    sa.Column('component_key', sa.String(length=100), nullable=False),
    sa.Column('impact_level', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_impact_events')
    op.drop_table('incident_alarm_events')
    op.drop_table('simulation_runs')
    op.drop_table('alarm_events')
    op.drop_table('sensor_observations')
    op.drop_table('incidents')
    op.drop_table('variable_statistics')
    op.drop_table('tep_runs')
    op.drop_table('readiness_answers')
    op.drop_table('infrastructure_dependencies')
    op.drop_table('bcm_profiles')
    op.drop_table('sensor_variables')
    op.drop_table('readiness_questions')
    op.drop_table('readiness_assessments')
    op.drop_table('raw_dataset_files')
    op.drop_table('infrastructure_components')
    # ### end Alembic commands ###
